spring:
  application:
    name: weather

  datasource:
    url: jdbc:h2:mem:weatherdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    properties:
      show-sql: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  quartz:
    job-store-type: memory

token:
  gridforecast: "360ywIHzsbc2E7bi"
  openweathermap: "a40e6ab34e1681f5773ba6e93fa11db0"

scheduler: "0 0/5 * ? * * *"